import { FoodCategory } from '@/types/model/food-categories';

export const foodCategoriesSample: FoodCategory[] = [
  {
    id: 1,
    name: 'Pizza',
    slug: 'pizza',
    parentId: 0,
    displayOrder: 1,
    image: require('@/assets/images/products/pizza.png'),
    counts: { children: 3, primaryProducts: 48, productLinks: 52 },
    children: [
      {
        id: 101,
        name: 'Classic Pizza',
        slug: 'classic-pizza',
        parentId: 1,
        displayOrder: 1,
        image: require('@/assets/images/products/pizza.png'),
        counts: { children: 0, primaryProducts: 18, productLinks: 20 },
        children: [],
      },
      {
        id: 102,
        name: 'Pepperoni Pizza',
        slug: 'pepperoni-pizza',
        parentId: 1,
        displayOrder: 2,
        image: require('@/assets/images/products/pizza.png'),
        counts: { children: 0, primaryProducts: 12, productLinks: 12 },
        children: [],
      },
      {
        id: 103,
        name: 'Vegetarian Pizza',
        slug: 'vegetarian-pizza',
        parentId: 1,
        displayOrder: 3,
        image: require('@/assets/images/products/pizza.png'),
        counts: { children: 0, primaryProducts: 8, productLinks: 9 },
        children: [],
      },
    ],
  },
  {
    id: 2,
    name: 'Burgers',
    slug: 'burgers',
    parentId: 0,
    displayOrder: 2,
    image: require('@/assets/images/products/burger.png'),
    counts: { children: 2, primaryProducts: 36, productLinks: 40 },
    children: [
      {
        id: 201,
        name: 'Beef Burgers',
        slug: 'beef-burgers',
        parentId: 2,
        displayOrder: 1,
        image: require('@/assets/images/products/burger.png'),
        counts: { children: 0, primaryProducts: 16, productLinks: 18 },
        children: [],
      },
      {
        id: 202,
        name: 'Chicken Burgers',
        slug: 'chicken-burgers',
        parentId: 2,
        displayOrder: 2,
        image: require('@/assets/images/products/burger.png'),
        counts: { children: 0, primaryProducts: 12, productLinks: 12 },
        children: [],
      },
    ],
  },
  {
    id: 4,
    name: 'Fried Chicken',
    slug: 'fried-chicken',
    parentId: 0,
    displayOrder: 4,
    image: require('@/assets/images/products/fried-chicken.png'),
    counts: { children: 2, primaryProducts: 22, productLinks: 24 },
    children: [
      {
        id: 401,
        name: 'Chicken Wings',
        slug: 'chicken-wings',
        parentId: 4,
        displayOrder: 1,
        image: require('@/assets/images/products/fried-chicken.png'),
        counts: { children: 0, primaryProducts: 10, productLinks: 10 },
        children: [],
      },
      {
        id: 402,
        name: 'Chicken Tenders',
        slug: 'chicken-tenders',
        parentId: 4,
        displayOrder: 2,
        image: require('@/assets/images/products/fried-chicken.png'),
        counts: { children: 0, primaryProducts: 8, productLinks: 9 },
        children: [],
      },
    ],
  },
  {
    id: 5,
    name: 'Salads',
    slug: 'salads',
    parentId: 0,
    displayOrder: 5,
    image: require('@/assets/images/products/salad.png'),
    counts: { children: 2, primaryProducts: 18, productLinks: 19 },
    children: [
      {
        id: 501,
        name: 'Caesar Salad',
        slug: 'caesar-salad',
        parentId: 5,
        displayOrder: 1,
        image: require('@/assets/images/products/salad.png'),
        counts: { children: 0, primaryProducts: 6, productLinks: 6 },
        children: [],
      },
      {
        id: 502,
        name: 'Greek Salad',
        slug: 'greek-salad',
        parentId: 5,
        displayOrder: 2,
        image: require('@/assets/images/products/salad.png'),
        counts: { children: 0, primaryProducts: 5, productLinks: 5 },
        children: [],
      },
    ],
  },
  {
    id: 6,
    name: 'Desserts',
    slug: 'desserts',
    parentId: 0,
    displayOrder: 6,
    image: require('@/assets/images/products/pancakes.png'),
    counts: { children: 3, primaryProducts: 26, productLinks: 30 },
    children: [
      {
        id: 601,
        name: 'Ice Cream',
        slug: 'ice-cream',
        parentId: 6,
        displayOrder: 1,
        image: require('@/assets/images/products/ice-cream.png'),
        counts: { children: 0, primaryProducts: 10, productLinks: 12 },
        children: [],
      },
      {
        id: 602,
        name: 'Cakes',
        slug: 'cakes',
        parentId: 6,
        displayOrder: 2,
        image: require('@/assets/images/products/panna-cotta.png'),
        counts: { children: 0, primaryProducts: 8, productLinks: 8 },
        children: [],
      },
      {
        id: 603,
        name: 'Donuts',
        slug: 'donuts',
        parentId: 6,
        displayOrder: 3,
        image: require('@/assets/images/products/donut.png'),
        counts: { children: 0, primaryProducts: 6, productLinks: 6 },
        children: [],
      },
    ],
  },
  {
    id: 7,
    name: 'Drinks',
    slug: 'drinks',
    parentId: 0,
    displayOrder: 7,
    image: require('@/assets/images/products/drink.png'),
    counts: { children: 3, primaryProducts: 34, productLinks: 38 },
    children: [
      {
        id: 701,
        name: 'Coffee',
        slug: 'coffee',
        parentId: 7,
        displayOrder: 1,
        image: require('@/assets/images/products/coffee.png'),
        counts: { children: 0, primaryProducts: 12, productLinks: 14 },
        children: [],
      },
      {
        id: 702,
        name: 'Milk Tea',
        slug: 'milk-tea',
        parentId: 7,
        displayOrder: 2,
        image: require('@/assets/images/products/bubble-tea.png'),
        counts: { children: 0, primaryProducts: 10, productLinks: 10 },
        children: [],
      },
      {
        id: 703,
        name: 'Cocktail',
        slug: 'cocktail',
        parentId: 7,
        displayOrder: 3,
        image: require('@/assets/images/products/cocktail.png'),
        counts: { children: 0, primaryProducts: 8, productLinks: 9 },
        children: [],
      },
    ],
  },
];
